# Generated by Django 5.1.1 on 2024-11-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bankaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('account_no', models.CharField(max_length=20)),
                ('owner_name', models.CharField(max_length=15)),
                ('owner_lastname', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=20)),
                ('accountType', models.CharField(max_length=15)),
                ('securitycode', models.CharField(max_length=10)),
                ('balance', models.CharField(max_length=100)),
            ],
        ),
    ]
